name: Java Maven CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'alualuew/TheArcWebShop'
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./backend/pom.xml 

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify --file ./backend/pom.xml 
    - run: mkdir staging && cp ./backend/target/*.jar staging 
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
